// src/components/navigation/AvatarTriggerShell.tsx
'use client'; import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ChevronDown, LogOut, Search, User as UserIcon, X,
} from 'lucide-react';
import { useEffect, useRef, useState } from 'react'; import { Avatar } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { useLogout } from '@/features/auth/hooks/useLogout'; type AvatarTriggerVariant = 'desktop' | 'mobile'; type AvatarTriggerShellProps = Readonly<{ variant?: AvatarTriggerVariant; avatarSrc?: string | null; displayName?: string; username?: string;
}>; type MenuItem = Readonly<{ label: string; href: string; icon: typeof Search;
}>; const MENU_ITEMS: readonly MenuItem[] = [ { label: 'Timeline', href: '/timeline', icon: UserIcon, }, { label: 'Explore', href: '/explore', icon: Search, }, { label: 'Profile', href: '/profile', icon: UserIcon, },
] as const; const AvatarIdentity = ({ avatarSrc, displayName,
}: Readonly<{ avatarSrc: string | null; displayName: string;
}>) => { return ( <Avatar src={avatarSrc} alt={`${displayName} avatar`} fallbackText={displayName} size='md' /> );
}; const useDropdownLifecycle = ( open: boolean, setOpen: React.Dispatch<React.SetStateAction<boolean>>, containerRef?: React.RefObject<HTMLDivElement | null>
) => { const pathname = usePathname(); useEffect(() => { setOpen(false); }, [pathname, setOpen]); useEffect(() => { if (!open) { return; } const containerElement = containerRef?.current ?? null; const handleEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setOpen(false); } }; const handlePointerDown = (event: MouseEvent | TouchEvent) => { if (!containerElement) { return; } if (!containerElement.contains(event.target as Node)) { setOpen(false); } }; document.addEventListener('keydown', handleEscape); if (containerElement) { document.addEventListener('mousedown', handlePointerDown); document.addEventListener('touchstart', handlePointerDown); } return () => { document.removeEventListener('keydown', handleEscape); if (containerElement) { document.removeEventListener('mousedown', handlePointerDown); document.removeEventListener('touchstart', handlePointerDown); } }; }, [open, setOpen, containerRef]);
}; const DesktopMenu = ({ avatarSrc, displayName, username,
}: Readonly<{ avatarSrc: string | null; displayName: string; username?: string;
}>) => { const { logout, isLoggingOut } = useLogout(); const [open, setOpen] = useState(false); const containerRef = useRef<HTMLDivElement | null>(null); useDropdownLifecycle(open, setOpen, containerRef); return ( <div ref={containerRef} className='relative'> <button type='button' onClick={() => setOpen((previous) => !previous)} className='inline-flex items-center gap-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring' aria-label={`Open profile menu for ${displayName}`} aria-expanded={open} > <AvatarIdentity avatarSrc={avatarSrc} displayName={displayName} /> <span className='max-w-[9rem] truncate leading-6 text-foreground'> {displayName} </span> <ChevronDown className={`h-4 w-4 shrink-0 text-muted-foreground transition-transform ${ open ? 'rotate-180' : '' }`} aria-hidden='true' /> </button> {open ? ( <div className='absolute right-0 top-[calc(100%+0.75rem)] z-[70] w-56 overflow-hidden border border-border bg-card shadow-[0_18px_40px_rgba(0,0,0,0.35)]'> <div className='border-b border-border px-4 py-3'> <p className='truncate text-sm text-card-foreground'> {displayName} </p> {username ? ( <p className='mt-1 truncate text-xs text-muted-foreground'> @{username} </p> ) : null} </div> <nav className='flex flex-col py-2'> {MENU_ITEMS.map((item) => { const Icon = item.icon; return ( <Link key={item.label} href={item.href} onClick={() => setOpen(false)} className='inline-flex items-center gap-3 px-4 py-3 text-sm font-medium text-card-foreground transition-colors hover:bg-muted' > <Icon className='h-4 w-4' aria-hidden='true' /> <span>{item.label}</span> </Link> ); })} <button type='button' onClick={() => { setOpen(false); logout(); }} disabled={isLoggingOut} className='inline-flex items-center gap-3 px-4 py-3 text-left text-sm font-medium text-destructive transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-70' > <LogOut className='h-4 w-4' aria-hidden='true' /> <span>{isLoggingOut ? 'Logging out...' : 'Logout'}</span> </button> </nav> </div> ) : null} </div> );
}; const MobileOverlayMenu = ({ avatarSrc, displayName, username,
}: Readonly<{ avatarSrc: string | null; displayName: string; username?: string;
}>) => { const { logout, isLoggingOut } = useLogout(); const [open, setOpen] = useState(false); useDropdownLifecycle(open, setOpen); return ( <> <button type='button' onClick={() => setOpen(true)} className='inline-flex items-center justify-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring' aria-label={`Open profile menu for ${displayName}`} aria-expanded={open} > <AvatarIdentity avatarSrc={avatarSrc} displayName={displayName} /> </button> {open ? ( <div className='fixed inset-0 z-[80] md:hidden'> <div className='absolute inset-0 bg-black/70 backdrop-blur-sm' aria-hidden='true' /> <section className='absolute inset-0 flex min-h-screen flex-col bg-shell-background text-foreground'> <header className='relative flex items-center justify-between border-b border-border/80 px-4 py-5'> <div className='flex min-w-0 items-center gap-3'> <AvatarIdentity avatarSrc={avatarSrc} displayName={displayName} /> <div className='min-w-0'> <p className='truncate text-foreground'> {displayName} </p> {username ? ( <p className='mt-1 truncate text-sm text-muted-foreground'> @{username} </p> ) : null} </div> </div> <button type='button' onClick={() => setOpen(false)} className='absolute right-5 top-5 inline-flex h-6 w-6 items-center justify-center text-white/90 transition-colors hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring' aria-label='Close account menu' > <X className='h-6 w-6' aria-hidden='true' /> </button> </header> <nav className='flex flex-col px-4 py-4'> {MENU_ITEMS.map((item) => { const Icon = item.icon; return ( <Link key={item.label} href={item.href} onClick={() => setOpen(false)} className='inline-flex items-center gap-3 border-b border-border/60 px-1 py-4 font-medium text-foreground transition-colors hover:text-primary' > <Icon className='h-5 w-5' aria-hidden='true' /> <span>{item.label}</span> </Link> ); })} <Button type='button' variant='destructive' size='lg' onClick={() => { setOpen(false); logout(); }} disabled={isLoggingOut} className='mt-6 w-full justify-center gap-3 ' > <LogOut className='h-5 w-5' aria-hidden='true' /> <span>{isLoggingOut ? 'Logging out...' : 'Logout'}</span> </Button> </nav> </section> </div> ) : null} </> );
}; const AvatarTriggerShell = ({ variant = 'desktop', avatarSrc = '/assets/avatar/avatar-placeholder.jpg', displayName = 'User', username,
}: AvatarTriggerShellProps) => { if (variant === 'mobile') { return ( <MobileOverlayMenu avatarSrc={avatarSrc} displayName={displayName} username={username} /> ); } return ( <DesktopMenu avatarSrc={avatarSrc} displayName={displayName} username={username} /> );
}; export default AvatarTriggerShell;
